INSERT INTO "User" (
    "id",
    "email",
    "passwordHash",
    "displayName",
    "status",
    "createdAt",
    "updatedAt"
)
VALUES (
    'cmseedcoach000000000000000',
    'system.seeded-drills@snooker.local',
    'inactive-system-account',
    'Snooker OS Coach',
    'INACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO UPDATE SET
    "displayName" = EXCLUDED."displayName",
    "status" = EXCLUDED."status",
    "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "DrillTemplate" (
    "id",
    "name",
    "category",
    "difficulty",
    "description",
    "goal",
    "rules",
    "successCriteria",
    "metricsSchemaJson",
    "defaultTableLayoutJson",
    "tags",
    "visibility",
    "createdByUserId",
    "createdAt",
    "updatedAt"
)
VALUES
(
    'cmseeddrill000000000000001',
    'Контроль прямого удара',
    'cue_action',
    'beginner',
    'Базовая тренировка на ровный кий, стабильную стойку и попадание в центр белого без лишнего бокового вращения.',
    'Собрать надежную прямую линию удара перед сериями на забивание и позиционную игру.',
    'Поставь белый на линию коричневого, красный по центру стола. Выполни 20 ударов в одном темпе. После каждого удара отмечай, ушел ли белый с линии.',
    'Минимум 16 из 20 ударов проходят по линии, белый после контакта остается в центральном коридоре.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"line_hits","label":"Удары по линии","type":"number","required":true},{"key":"cue_ball_deviation_mm","label":"Отклонение белого","type":"number","unit":"мм","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-straight-cueing","tableSize":"full-size","balls":[{"id":"white","color":"white","x":740,"y":889,"visible":true},{"id":"red-1","color":"red","x":1785,"y":889,"visible":true}],"targetZones":[{"id":"center-corridor","type":"rectangle","x":720,"y":819,"width":2140,"height":140,"label":"Центральный коридор"}],"shotPaths":[{"id":"cue-line","from":{"x":740,"y":889},"to":{"x":1785,"y":889},"label":"Белый в центр красного"},{"id":"object-line","from":{"x":1785,"y":889},"to":{"x":2780,"y":889},"label":"Продолжение линии"}],"annotations":[{"id":"tempo","text":"Один темп, пауза перед ударом","at":{"x":980,"y":720}}]}$layout$::jsonb,
    ARRAY['старт', 'техника', '15мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000002',
    'Длинный красный в угол',
    'potting',
    'intermediate',
    'Тренировка длинного забивания с контролем прицельной линии и спокойным ускорением кия.',
    'Повысить процент длинных красных и убрать форсированный удар на дальних шарах.',
    'Играй красный в дальний верхний угол из позиции на схеме. Серия 5 подходов по 10 ударов, перед каждым ударом фиксируй точку контакта.',
    'В каждом подходе минимум 5 забитых красных, без потери стойки и с повторяемым временем подготовки.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"pots","label":"Забито","type":"number","required":true},{"key":"pre_shot_time_ms","label":"Время подготовки","type":"time_ms","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-long-red","tableSize":"full-size","balls":[{"id":"white","color":"white","x":820,"y":1190,"visible":true},{"id":"red-1","color":"red","x":2470,"y":430,"visible":true}],"targetZones":[{"id":"potting-pocket","type":"circle","x":3505,"y":70,"radius":115,"label":"Верхний угол"},{"id":"cue-ball-safe-zone","type":"circle","x":1980,"y":980,"radius":180,"label":"Контроль белого"}],"shotPaths":[{"id":"cue-to-red","from":{"x":820,"y":1190},"to":{"x":2470,"y":430},"label":"Линия удара"},{"id":"red-to-pocket","from":{"x":2470,"y":430},"to":{"x":3505,"y":70},"label":"Красный в угол"}],"annotations":[{"id":"sight","text":"Проверить линию стоя за белым","at":{"x":1240,"y":1320}}]}$layout$::jsonb,
    ARRAY['забивание', 'длинные', '30мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000003',
    'Черный с выходом на синий',
    'positional_play',
    'intermediate',
    'Позиционная тренировка: забить черный и вывести белый в рабочую зону для продолжения серии через синий.',
    'Научиться контролировать силу после черного и не оставлять белый приклеенным к борту.',
    'Играй черный в правый верхний угол. После контакта белый должен вернуться в отмеченную зону около синего. 4 подхода по 8 ударов.',
    'Не менее 60% забитых черных и не менее 50% попаданий белым в целевую зону.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"pots","label":"Забито","type":"number","required":true},{"key":"position_hits","label":"Выход в зону","type":"number","required":true},{"key":"success_rate","label":"Успех","type":"percentage","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-black-to-blue","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2550,"y":1030,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"blue","color":"blue","x":1784.5,"y":889,"visible":true}],"targetZones":[{"id":"blue-side-position","type":"circle","x":1870,"y":760,"radius":180,"label":"Зона выхода"},{"id":"corner-pocket","type":"circle","x":3505,"y":70,"radius":115,"label":"Угол для черного"}],"shotPaths":[{"id":"cue-to-black","from":{"x":2550,"y":1030},"to":{"x":3245,"y":889},"label":"Черный"},{"id":"black-to-pocket","from":{"x":3245,"y":889},"to":{"x":3505,"y":70},"label":"В угол"},{"id":"cue-ball-position","from":{"x":2550,"y":1030},"to":{"x":1870,"y":760},"label":"Белый в зону"}],"annotations":[{"id":"pace","text":"Сила важнее винта","at":{"x":2200,"y":650}}]}$layout$::jsonb,
    ARRAY['позиция', 'цветные', '25мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000004',
    'Малый брейк у розового',
    'break_building',
    'advanced',
    'Серия вокруг розового и черного для развития выбора очередного шара, темпа и короткого контроля белого.',
    'Собрать устойчивый мини-брейк из красных вокруг розового с возвратом на черный или розовый.',
    'Начни с выбранного красного у розового. После каждого красного играй цветной и возвращайся в одну из отмеченных зон. Работай сериями по 6 красных.',
    'Серия 12+ очков минимум в трех из пяти попыток, без выхода белого к борту после цветного.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"break_points","label":"Очки серии","type":"number","required":true},{"key":"max_run","label":"Лучший брейк","type":"number","required":false},{"key":"position_errors","label":"Ошибки позиции","type":"number","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pink-break","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2300,"y":1110,"visible":true},{"id":"pink","color":"pink","x":2603,"y":889,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"red-1","color":"red","x":2705,"y":800,"visible":true},{"id":"red-2","color":"red","x":2760,"y":905,"visible":true},{"id":"red-3","color":"red","x":2825,"y":1010,"visible":true},{"id":"red-4","color":"red","x":2900,"y":840,"visible":true},{"id":"red-5","color":"red","x":2965,"y":955,"visible":true},{"id":"red-6","color":"red","x":3040,"y":1060,"visible":true}],"targetZones":[{"id":"pink-zone","type":"circle","x":2580,"y":980,"radius":170,"label":"Выход на розовый"},{"id":"black-zone","type":"circle","x":3040,"y":780,"radius":190,"label":"Выход на черный"}],"shotPaths":[{"id":"first-red","from":{"x":2300,"y":1110},"to":{"x":2705,"y":800},"label":"1. Красный"},{"id":"red-to-middle","from":{"x":2705,"y":800},"to":{"x":1784,"y":0},"label":"Красный в середину"},{"id":"cue-to-zone","from":{"x":2300,"y":1110},"to":{"x":2580,"y":980},"label":"Белый под цветной"}],"annotations":[{"id":"choice","text":"Выбирай следующий красный до удара по цветному","at":{"x":2380,"y":650}}]}$layout$::jsonb,
    ARRAY['серия', 'брейк', '40мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000005',
    'Безопасный отыгрыш в baulk',
    'safety',
    'intermediate',
    'Классический защитный отыгрыш: отправить объектный шар к верхней части стола и вернуть белый в baulk за цветные.',
    'Сформировать надежный защитный удар, который оставляет сопернику длинный сложный ответ.',
    'Сыграй тонкий контакт по красному. Белый возвращается в отмеченную baulk-зону через борт, красный уходит от простого луза.',
    'В 7 из 10 попыток белый заканчивает в baulk-зоне, а сопернику не остается прямого короткого забивания.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"safe_leaves","label":"Безопасные позиции","type":"number","required":true},{"key":"cue_ball_zone_hits","label":"Белый в baulk","type":"number","required":true}]}$metrics$::jsonb,
    $layout${"id":"seed-baulk-safety","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2860,"y":1180,"visible":true},{"id":"red-1","color":"red","x":2380,"y":650,"visible":true},{"id":"yellow","color":"yellow","x":736.6,"y":305,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true}],"targetZones":[{"id":"baulk-cover","type":"rectangle","x":360,"y":260,"width":720,"height":1258,"label":"Белый за цветными"},{"id":"red-safe-area","type":"rectangle","x":2500,"y":160,"width":760,"height":420,"label":"Красный к верхнему борту"}],"shotPaths":[{"id":"thin-red","from":{"x":2860,"y":1180},"to":{"x":2380,"y":650},"label":"Тонкий контакт"},{"id":"cue-ball-safety","from":{"x":2860,"y":1180},"to":{"x":620,"y":960},"cushions":[{"x":3180,"y":1580},{"x":1180,"y":1720}],"label":"Белый в baulk"}],"annotations":[{"id":"thin","text":"Тоньше контакт, меньше риска оставить шар","at":{"x":2060,"y":480}}]}$layout$::jsonb,
    ARRAY['safety', 'тактика', '25мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000006',
    'Выход из снукера через борт',
    'snooker_escape',
    'intermediate',
    'Тренировка расчета угла от борта и контроля скорости при выходе из снукера.',
    'Научиться стабильно попадать в объектный шар через один борт и оставлять безопасный ответ.',
    'Белый закрыт цветными. Рассчитай угол от нижнего борта и попади в красный. Начни без требования забивания, затем добавь контроль оставшейся позиции.',
    'Минимум 8 попаданий в красный из 10 попыток, не более двух фолов по скорости или промаху.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"escapes","label":"Попадания в шар","type":"number","required":true},{"key":"fouls","label":"Фолы","type":"number","required":false},{"key":"safety_quality","label":"Качество отыгрыша","type":"percentage","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-one-cushion-escape","tableSize":"full-size","balls":[{"id":"white","color":"white","x":610,"y":1420,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"red-1","color":"red","x":2320,"y":500,"visible":true}],"targetZones":[{"id":"contact-window","type":"circle","x":2320,"y":500,"radius":120,"label":"Окно контакта"},{"id":"escape-finish","type":"rectangle","x":2100,"y":360,"width":620,"height":420,"label":"Безопасный сектор"}],"shotPaths":[{"id":"escape-line","from":{"x":610,"y":1420},"to":{"x":2320,"y":500},"cushions":[{"x":980,"y":1740}],"label":"Один борт"}],"annotations":[{"id":"angle","text":"Целься в точку на борту, не в красный","at":{"x":820,"y":1600}}]}$layout$::jsonb,
    ARRAY['снукер', 'борта', '20мин']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000007',
    'Финальный черный под давлением',
    'pressure_training',
    'advanced',
    'Повторяемая ситуация решающего черного: рутина, дыхание и выполнение одного качественного удара под счет.',
    'Сделать предударную рутину устойчивой, когда цена удара выше обычной тренировки.',
    'Перед каждым ударом назови счет и выполни полную рутину. Серия заканчивается после промаха или после 10 забитых подряд.',
    'Лучшая серия 7+ финальных черных подряд с одинаковой рутиной и без ускорения подготовки.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"pots","label":"Забито","type":"number","required":true},{"key":"best_streak","label":"Лучшая серия подряд","type":"number","required":true},{"key":"routine_kept","label":"Рутина сохранена","type":"boolean","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-final-black-pressure","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2830,"y":1075,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true}],"targetZones":[{"id":"black-pocket","type":"circle","x":3505,"y":70,"radius":115,"label":"Черный в угол"},{"id":"cue-control","type":"circle","x":2850,"y":760,"radius":180,"label":"Контроль белого"}],"shotPaths":[{"id":"cue-to-black","from":{"x":2830,"y":1075},"to":{"x":3245,"y":889},"label":"Черный"},{"id":"black-to-pocket","from":{"x":3245,"y":889},"to":{"x":3505,"y":70},"label":"В угол"}],"annotations":[{"id":"routine","text":"Дыхание, взгляд, пауза, удар","at":{"x":2460,"y":1260}}]}$layout$::jsonb,
    ARRAY['давление', 'рутина', 'матч']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000008',
    '6 красных: контроль серии',
    'match_simulation',
    'advanced',
    'Матчевая мини-серия из шести красных с выбором правильного цветного и фиксацией ошибок решения.',
    'Перевести технические навыки в игровой сценарий: план, исполнение, корректировка после ошибки.',
    'Разложи шесть красных как на схеме. Играй серию по правилам матча: красный, цветной, следующий красный. После завершения отметь ошибку решения или исполнения.',
    'Средний результат 18+ очков за попытку и понятная причина остановки каждой серии.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"break_points","label":"Очки серии","type":"number","required":true},{"key":"max_run","label":"Лучший брейк","type":"number","required":true},{"key":"decision_errors","label":"Ошибки решения","type":"number","required":false},{"key":"execution_errors","label":"Ошибки исполнения","type":"number","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-six-red-match","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2140,"y":980,"visible":true},{"id":"yellow","color":"yellow","x":736.6,"y":305,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true},{"id":"blue","color":"blue","x":1784.5,"y":889,"visible":true},{"id":"pink","color":"pink","x":2603,"y":889,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"red-1","color":"red","x":2450,"y":720,"visible":true},{"id":"red-2","color":"red","x":2520,"y":1010,"visible":true},{"id":"red-3","color":"red","x":2680,"y":820,"visible":true},{"id":"red-4","color":"red","x":2790,"y":1100,"visible":true},{"id":"red-5","color":"red","x":2940,"y":760,"visible":true},{"id":"red-6","color":"red","x":3060,"y":980,"visible":true}],"targetZones":[{"id":"blue-pink-choice","type":"polygon","points":[{"x":1780,"y":650},{"x":2690,"y":690},{"x":2740,"y":1080},{"x":1800,"y":1120}],"label":"Зона выбора цветного"},{"id":"next-red-zone","type":"circle","x":2700,"y":900,"radius":260,"label":"Следующий красный"}],"shotPaths":[{"id":"first-red","from":{"x":2140,"y":980},"to":{"x":2450,"y":720},"label":"1. Первый красный"},{"id":"red-to-pocket","from":{"x":2450,"y":720},"to":{"x":1784,"y":0},"label":"В среднюю"},{"id":"position-route","from":{"x":2140,"y":980},"to":{"x":2600,"y":890},"label":"Выбор цветного"}],"annotations":[{"id":"review","text":"После серии запиши: решение или исполнение","at":{"x":1680,"y":1260}}]}$layout$::jsonb,
    ARRAY['матч', 'серия', 'анализ']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "category" = EXCLUDED."category",
    "difficulty" = EXCLUDED."difficulty",
    "description" = EXCLUDED."description",
    "goal" = EXCLUDED."goal",
    "rules" = EXCLUDED."rules",
    "successCriteria" = EXCLUDED."successCriteria",
    "metricsSchemaJson" = EXCLUDED."metricsSchemaJson",
    "defaultTableLayoutJson" = EXCLUDED."defaultTableLayoutJson",
    "tags" = EXCLUDED."tags",
    "visibility" = EXCLUDED."visibility",
    "createdByUserId" = EXCLUDED."createdByUserId",
    "updatedAt" = CURRENT_TIMESTAMP;