INSERT INTO "DrillTemplate" (
    "id",
    "name",
    "category",
    "difficulty",
    "description",
    "goal",
    "rules",
    "successCriteria",
    "metricsSchemaJson",
    "defaultTableLayoutJson",
    "tags",
    "visibility",
    "createdByUserId",
    "createdAt",
    "updatedAt"
)
VALUES
(
    'cmseeddrill000000000000009',
    'Длинный красный с выходом под черный',
    'potting',
    'professional',
    'Профессиональная версия длинного красного: забивание должно сразу давать рабочий угол на черный или розовый.',
    'Соединить дальнее забивание с точным контролем первого выхода в серийной ситуации.',
    'Играй длинный красный в верхний угол. Белый после контакта должен прийти в отмеченную зону под черный. 6 подходов по 8 ударов, каждый удар с полной предударной рутиной.',
    'Минимум 55% забитых длинных красных и минимум 45% попаданий белым в позиционную зону.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"pots","label":"Забито","type":"number","required":true},{"key":"position_hits","label":"Выход в зону","type":"number","required":true},{"key":"cue_ball_deviation_mm","label":"Отклонение белого","type":"number","unit":"мм","required":false},{"key":"pre_shot_time_ms","label":"Время подготовки","type":"time_ms","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-long-red-black-side","tableSize":"full-size","balls":[{"id":"white","color":"white","x":780,"y":1240,"visible":true},{"id":"red-1","color":"red","x":2460,"y":455,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"pink","color":"pink","x":2603,"y":889,"visible":true}],"targetZones":[{"id":"black-side-position","type":"circle","x":3010,"y":760,"radius":190,"label":"Зона под черный"},{"id":"long-red-pocket","type":"circle","x":3505,"y":70,"radius":115,"label":"Верхний угол"}],"shotPaths":[{"id":"red-to-pocket","from":{"x":2460,"y":455},"to":{"x":3505,"y":70},"label":"Красный в угол"},{"id":"cue-ball-route","from":{"x":780,"y":1240},"to":{"x":3010,"y":760},"label":"Белый под черный"}],"annotations":[{"id":"routine","text":"Пауза на линии, затем один темп","at":{"x":1020,"y":1370}}]}$layout$::jsonb,
    ARRAY['профессионал', 'длинные', 'позиция']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000010',
    'Три шара у черного: клиренс',
    'break_building',
    'professional',
    'Компактный паттерн для клиренса вокруг черного, где ошибка выбора следующего красного сразу ломает серию.',
    'Закрепить чтение микропозиций и короткий контроль белого в зоне черного.',
    'Разложи три красных вокруг черного. Играй красный, черный, красный, черный, красный, черный. Повтори 10 серий, меняя первый красный.',
    'Минимум 18 очков в 6 из 10 серий и не более двух позиционных ошибок за тренировку.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"break_points","label":"Очки серии","type":"number","required":true},{"key":"max_run","label":"Лучший брейк","type":"number","required":true},{"key":"position_errors","label":"Ошибки позиции","type":"number","required":false},{"key":"execution_errors","label":"Ошибки исполнения","type":"number","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-three-ball-black-clearance","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2920,"y":1110,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"red-1","color":"red","x":2870,"y":770,"visible":true},{"id":"red-2","color":"red","x":2925,"y":970,"visible":true},{"id":"red-3","color":"red","x":3060,"y":1040,"visible":true}],"targetZones":[{"id":"black-working-zone","type":"circle","x":3000,"y":900,"radius":230,"label":"Рабочая зона черного"}],"shotPaths":[{"id":"first-red","from":{"x":2920,"y":1110},"to":{"x":2870,"y":770},"label":"Первый красный"},{"id":"black-return","from":{"x":2920,"y":1110},"to":{"x":3245,"y":889},"label":"Возврат на черный"}],"annotations":[{"id":"choice","text":"Следующий красный выбран до удара по черному","at":{"x":2360,"y":650}}]}$layout$::jsonb,
    ARRAY['профессионал', 'брейк', 'черный']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000011',
    'Двухходовая защитная ловушка',
    'tactical_play',
    'professional',
    'Тактическая тренировка на два визита: первый удар ограничивает варианты, второй закрепляет контроль стола.',
    'Научиться строить safety не одним ударом, а последовательностью с предсказуемым ответом соперника.',
    'Сыграй тонкий контакт по красному и верни белый в baulk. Во втором повторе усложни задачу: объектный шар должен остаться у длинного борта, а белый за цветными.',
    'В 7 из 10 попыток белый скрыт за цветными, объектный шар не оставляет прямого забивания, тактическая ошибка записана сразу.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"safe_leaves","label":"Безопасные позиции","type":"number","required":true},{"key":"cue_ball_zone_hits","label":"Белый в зоне","type":"number","required":true},{"key":"object_ball_zone_hits","label":"Объектный шар в зоне","type":"number","required":true},{"key":"tactical_errors","label":"Тактические ошибки","type":"number","required":false},{"key":"safety_quality","label":"Качество отыгрыша","type":"percentage","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-two-visit-containment","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2790,"y":1240,"visible":true},{"id":"red-1","color":"red","x":2240,"y":620,"visible":true},{"id":"yellow","color":"yellow","x":736.6,"y":305,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true}],"targetZones":[{"id":"cue-ball-baulk-lock","type":"rectangle","x":360,"y":260,"width":760,"height":1258,"label":"Белый за цветными"},{"id":"object-ball-rail-lock","type":"rectangle","x":2450,"y":135,"width":820,"height":260,"label":"Объектный шар у борта"}],"shotPaths":[{"id":"containment-contact","from":{"x":2790,"y":1240},"to":{"x":2240,"y":620},"label":"Тонкий контакт"},{"id":"cue-ball-lock","from":{"x":2790,"y":1240},"to":{"x":620,"y":940},"cushions":[{"x":3160,"y":1580},{"x":1250,"y":1720}],"label":"Белый в baulk"}],"annotations":[{"id":"plan","text":"Планируй ответ соперника до первого удара","at":{"x":1720,"y":520}}]}$layout$::jsonb,
    ARRAY['профессионал', 'тактика', 'safety']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000012',
    'Выход из снукера через два борта',
    'snooker_escape',
    'professional',
    'Сложный escape: контакт через два борта должен не только избежать фола, но и оставить безопасную позицию.',
    'Довести расчет углов и скорости до матчевого уровня под давлением штрафных очков.',
    'Белый закрыт цветными. Рассчитай двухбортный маршрут к красному. После контакта белый или красный должны уйти в безопасный сектор.',
    'Минимум 7 контактов из 10, не более двух фолов и минимум 5 безопасных оставлений.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"escapes","label":"Выходы из снукера","type":"number","required":true},{"key":"safe_leaves","label":"Безопасные позиции","type":"number","required":true},{"key":"fouls","label":"Фолы","type":"number","required":false},{"key":"escape_quality","label":"Качество выхода","type":"percentage","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-two-cushion-escape","tableSize":"full-size","balls":[{"id":"white","color":"white","x":650,"y":1390,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"blue","color":"blue","x":1784.5,"y":889,"visible":true},{"id":"red-1","color":"red","x":2460,"y":480,"visible":true}],"targetZones":[{"id":"contact-window","type":"circle","x":2460,"y":480,"radius":125,"label":"Окно контакта"},{"id":"safe-finish-sector","type":"rectangle","x":2200,"y":300,"width":680,"height":420,"label":"Безопасный сектор"}],"shotPaths":[{"id":"two-cushion-route","from":{"x":650,"y":1390},"to":{"x":2460,"y":480},"cushions":[{"x":1020,"y":1740},{"x":3380,"y":1470}],"label":"Два борта"}],"annotations":[{"id":"speed","text":"Скорость важнее тонкости контакта","at":{"x":980,"y":1580}}]}$layout$::jsonb,
    ARRAY['профессионал', 'снукер', 'борта']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000013',
    'Первая возможность: 8 красных',
    'match_simulation',
    'professional',
    'Матчевая симуляция первого шанса: восемь красных, выбор цветных и фиксация причины остановки серии.',
    'Повысить конверсию первого открытого шанса в решающее преимущество по очкам.',
    'Разложи восемь красных как на схеме. Играй как в матче до промаха или потери позиции. После каждой попытки запиши, где серия остановилась: решение или исполнение.',
    'Средний результат 32+ очка, минимум 3 серии 40+ очков из 8 попыток и понятная причина остановки каждой серии.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"break_points","label":"Очки серии","type":"number","required":true},{"key":"max_run","label":"Лучший брейк","type":"number","required":true},{"key":"first_chance_conversion","label":"Конверсия первого шанса","type":"percentage","required":false},{"key":"decision_errors","label":"Ошибки решения","type":"number","required":false},{"key":"execution_errors","label":"Ошибки исполнения","type":"number","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-first-chance-eight-reds","tableSize":"full-size","balls":[{"id":"white","color":"white","x":2130,"y":1020,"visible":true},{"id":"yellow","color":"yellow","x":736.6,"y":305,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true},{"id":"blue","color":"blue","x":1784.5,"y":889,"visible":true},{"id":"pink","color":"pink","x":2603,"y":889,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true},{"id":"red-1","color":"red","x":2380,"y":700,"visible":true},{"id":"red-2","color":"red","x":2470,"y":1010,"visible":true},{"id":"red-3","color":"red","x":2620,"y":790,"visible":true},{"id":"red-4","color":"red","x":2700,"y":1110,"visible":true},{"id":"red-5","color":"red","x":2860,"y":750,"visible":true},{"id":"red-6","color":"red","x":2960,"y":1020,"visible":true},{"id":"red-7","color":"red","x":3080,"y":820,"visible":true},{"id":"red-8","color":"red","x":3160,"y":1100,"visible":true}],"targetZones":[{"id":"color-choice-zone","type":"polygon","points":[{"x":1760,"y":640},{"x":3300,"y":670},{"x":3330,"y":1130},{"x":1770,"y":1160}],"label":"Зона выбора цветного"}],"shotPaths":[{"id":"opening-red","from":{"x":2130,"y":1020},"to":{"x":2380,"y":700},"label":"Первый красный"},{"id":"first-position","from":{"x":2130,"y":1020},"to":{"x":2600,"y":890},"label":"Первый выход"}],"annotations":[{"id":"review","text":"После серии: решение или исполнение","at":{"x":1580,"y":1280}}]}$layout$::jsonb,
    ARRAY['профессионал', 'матч', 'брейк']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cmseeddrill000000000000014',
    'Клиренс цветных по таймеру',
    'mental_routine',
    'professional',
    'Финальная серия по цветным с ограничением времени на подготовку, но без потери качества рутины.',
    'Сохранить ясную предударную рутину, когда темп матча требует быстрых решений.',
    'Играй желтый, зеленый, коричневый, синий, розовый, черный. На каждый удар 20 секунд подготовки. Серия повторяется 8 раз.',
    'Минимум 5 полных клиренсов из 8 и среднее время подготовки в целевом окне без ускоренного последнего удара.',
    $metrics${"version":1,"metrics":[{"key":"attempts","label":"Попытки","type":"number","required":true},{"key":"pots","label":"Забито","type":"number","required":true},{"key":"best_streak","label":"Лучшая серия подряд","type":"number","required":true},{"key":"routine_kept","label":"Рутина сохранена","type":"boolean","required":false},{"key":"pre_shot_time_ms","label":"Время подготовки","type":"time_ms","required":false},{"key":"pressure_errors","label":"Ошибки под давлением","type":"number","required":false}]}$metrics$::jsonb,
    $layout${"id":"seed-pro-shot-clock-colors","tableSize":"full-size","balls":[{"id":"white","color":"white","x":1520,"y":1040,"visible":true},{"id":"yellow","color":"yellow","x":736.6,"y":305,"visible":true},{"id":"green","color":"green","x":736.6,"y":1473,"visible":true},{"id":"brown","color":"brown","x":736.6,"y":889,"visible":true},{"id":"blue","color":"blue","x":1784.5,"y":889,"visible":true},{"id":"pink","color":"pink","x":2603,"y":889,"visible":true},{"id":"black","color":"black","x":3245,"y":889,"visible":true}],"targetZones":[{"id":"cue-ball-control-band","type":"rectangle","x":1180,"y":620,"width":1800,"height":560,"label":"Коридор контроля белого"}],"shotPaths":[{"id":"color-clearance-route","from":{"x":1520,"y":1040},"to":{"x":3245,"y":889},"label":"Маршрут клиренса"}],"annotations":[{"id":"clock","text":"20 секунд: дыхание, взгляд, пауза","at":{"x":1120,"y":520}}]}$layout$::jsonb,
    ARRAY['профессионал', 'рутина', 'цветные']::TEXT[],
    'system',
    'cmseedcoach000000000000000',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO UPDATE SET
    "name" = EXCLUDED."name",
    "category" = EXCLUDED."category",
    "difficulty" = EXCLUDED."difficulty",
    "description" = EXCLUDED."description",
    "goal" = EXCLUDED."goal",
    "rules" = EXCLUDED."rules",
    "successCriteria" = EXCLUDED."successCriteria",
    "metricsSchemaJson" = EXCLUDED."metricsSchemaJson",
    "defaultTableLayoutJson" = EXCLUDED."defaultTableLayoutJson",
    "tags" = EXCLUDED."tags",
    "visibility" = EXCLUDED."visibility",
    "createdByUserId" = EXCLUDED."createdByUserId",
    "updatedAt" = CURRENT_TIMESTAMP;
